name: hazemkallini
favicon: null
layout_spectrum: 0.5496726860292256
typography_spectrum: 0.12872464442625642
title: Personal space for Hazem Kallini
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dad8e3'
    - '#ca9a8c'
    - '#705250'
    - '#bc5759'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
